language: node_js
node_js:
- '4.1'
deploy:
  provider: npm
  email: philippevoinov@gmail.com
  api_key:
    secure: FpvJMmL/yzP3yPHzfZpoalDW/GNcw5io3TtVsqlm6/X+nOJrxntsgmiwubUw5wz7H3xzz+XWOrgAQALUkVOWJSdrHDk+/gJdlHUZcUHU/2tpGZDlyyfLgwkNug1swiiyglLR+A88q/kvoDlP5qmyUODu6MOfwLmnobkqLdGhhN1jyY28uabmEndWafqAnsQN30yn4WhBSyiC0K0ZtSu6QP6/FZpgxZ9P9emUIldGpfSBmsIFU/ZI3ShtQ/xL/ljZR3hiM00quM5kSsXyry2vfy0vLW5qr7cKSMsBhtyXRl4LT7TENfMEUFfRz7KLOiEJVz83jdnZoPGSy9G6PLHIySFsGzV9916DovGjit8MEPU+wvV5w96CDumoGdVU67O1FYB0Ltd7OJFraMJhXB+UmvGq5gjwwuQ6O92fxFdrNk9QvJlKs1bZ0ja+C18m56Awt65pLA9COjIu4z/2ClnMa5oALvbjxJ7h7yfZRdorCSDU8+rulkId4aLQBHCS24OrOzUu6DxwspOpBJFmSUuFPKYAyuq9LPFwAxZyTHsf7PaSWbMl4uRouoehK+3yzuHaLAV+c+4TMIr2DXpAZVUXp5tt54Os5lz7v4mhqL3ANP1yTV7ggq9QgIAjrIfBBjmoalJRfy9vvQi6rsIPPnTTeM+eU5VEO5egpJudxvHzcRA=
  on:
    tags: true
    repo: tehwalris/marugoto-pull
